[project]
name = "pyxledger"
version = "0.1.0"
description = "Library to interact with the Xledger API"
authors = [{ name = "David Skoland", email = "david.skoland@asterisk.digital" }]
requires-python = ">=3.11"

dependencies = [
    "graphql-core>=3.2",
    "requests>=2.28",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "setuptools",
    "wheel",
    "ruff",
    "tox",
    "tox-uv"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["tests"]

[tool.ruff]
line-length = 120
lint.select = ["E", "F"]
exclude = ["build", "dist", "venv"]
